--- #YAML:1.0
name:               Tenjin
version:            0.061
abstract:           Fast templating engine with support for embedded Perl.
author:
    - Ido Perlmuter <ido@ido50.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:          0
    HTML::Entities:  0
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
