---
abstract: 'Fast templating engine with support for embedded Perl.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
  Try::Tiny: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tenjin
requires:
  Carp: 0
  Fcntl: 0
  HTML::Entities: 0
  perl: 5.008
resources:
  homepage: http://github.com/ido50/Tenjin/tree
  repository: git://github.com/ido50/Tenjin.git
version: 0.070001
